/pujo/list is working
Pujo-Atlas-Kolkata/PujoAtlasKol-Backend pull request #3
Opened 2024-08-28 15:09 UTC by Sbasu2512

/pujo/list and query params API route coded.

2024-08-31 10:07 UTC, pnaskardev requested changes
1. Can we migrate to ModelViewset class based API Controllers instead of function based (reading the documentation should help you)

2024-08-31 11:56 UTC, Sbasu2512 commented
requested changes implmented. Also updated read me

2024-09-13 11:49 UTC, pnaskardev approved these changes

2024-09-13 11:51 UTC, pnaskardev approved these changes

2024-09-13 11:51 UTC, merged